export const data = [
  {
    id: 1,
    title: 'Large Detroit Style Pizza',
    order: 3213456785,
    amount: '$31.43',
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 2,
    title: 'Double Decker Club With Fries. Pickles, extra side avacado',
    order: 9874563245,
    amount: '$12.99',
    status: 'Delivered',
    name: 'Cathy',
  },
  {
    id: 3,
    title: 'Family Sized Lobster Dinner',
    order: 3456781234,
    amount: '$320.00',
    status: 'In Progress',
    name: 'Alexander',
  },
  {
    id: 4,
    title: 'Style Pizza',
    order: 3213456785,
    amount: '$31.43',
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 5,
    title: 'Club With Fries. Pickles, extra side avacado',
    order: 9874563245,
    amount: '$12.99',
    status: 'Delivered',
    name: 'Cathy',
  },
  {
    id: 6,
    title: 'Lobster Dinner',
    order: 3456781234,
    amount: '$320.00',
    status: 'In Progress',
    name: 'Alexander',
  },
  {
    id: 7,
    title: 'Pizza pepperoni',
    order: 3213456785,
    amount: '$31.43',
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 8,
    title: 'Double Decker Club With Fries. Pickles, extra side avacado',
    order: 9874563245,
    amount: '$12.99',
    status: 'Delivered',
    name: 'Cathy',
  },
  {
    id: 9,
    title: 'Family Sized Lobster Dinner',
    order: 3456781234,
    amount: '$320.00',
    status: 'In Progress',
    name: 'Alex',
  },
  {
    id: 10,
    title: 'Large Detroit Style Pizza',
    order: 3213456785,
    amount: '$31.43',
    status: 'Pending',
    name: 'Dave',
  },
  {
    id: 11,
    title: 'Double Decker Club With Fries. Pickles, extra side avacado',
    order: 9874563245,
    amount: '$12.99',
    status: 'Delivered',
    name: 'Dima',
  },
  {
    id: 12,
    title: 'Family Sized Dinner',
    order: 3456781234,
    amount: '$320.00',
    status: 'Stopped',
    name: 'Alex',
  },
];
